const ADD = 'ADD';
const SUBTRACT = 'SUBTRACT';
const RESTORE = 'RESTORE';
const LOGIN = 'LOGIN';
const LOGOUT = 'LOGOUT';
const GETUSERDATA = 'GETUSERDATA';


export default {
  ADD, SUBTRACT, RESTORE, LOGIN, LOGOUT, GETUSERDATA
};
