const ADD = 'ADD';
const SUBTRACT = 'SUBTRACT';
const RESTORE = 'RESTORE';
const LOGIN = 'LOGIN';
const LOGOUT = 'LOGOUT';
const GETUSERDATA_PENDING = 'GET_USER_DATA_PENDING';
const GETUSERDATA_SUCCESS = 'GET_USER_DATA_SUCCESS';
const GETUSERDATA_FAILED = 'GET_USER_DATA_FAILED';


export default {
  ADD,
  SUBTRACT,
  RESTORE,
  LOGIN,
  LOGOUT,
  GETUSERDATA_PENDING,
  GETUSERDATA_SUCCESS,
  GETUSERDATA_FAILED
};
