const ERROR_MSG = 'ERROR_MSG';
const REGISTER_PENDING = 'REGISTER_PENDING';
const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
const LOGIN_PENDING = 'LOGIN_PENDING';
const LOGIN_SUCCESS = 'LOGIN_SUCCESS';


export default {
  ERROR_MSG, REGISTER_PENDING, REGISTER_SUCCESS, LOGIN_PENDING, LOGIN_SUCCESS
};
